### ISSUE TITLE
How to typing this in Angular 6?

### ISSUE THREAD

**Issue by leoGrg** [david476/bicubic-interpolate#5]
Hi,

I'm trying to include this library in my Angular 6 project but I have a typing problem.
Even if I declare **'bicubic-interpolate'** module in my .d.ts file
example: `declare module 'bicubic-interpolate';`

Do you have a solution for TypeScript?

Best regards,

**Comment by david-boles** [comment]
@leoGrg Thanks for making an issue! I haven't had as much time to work on this library (and the project I made it for) as I would have liked, it's still untested and looks like the dependencies could use version bumps, but I'm happy to help make this work for you if you want!

I don't have a ton of TS experience, any chance you'd be able to figure it out and submit a PR? Otherwise I wouldn't mind learning so I might be able to find the time to do it myself.

**Comment by leoGrg** [comment]
@david-boles Thanks for your answer, 
I have successfully done it by declaring:
```
// @ts-ignore
import * as bicubic from 'bicubic-interpolate'
```

**Comment by BrUSomania** [comment]
@leoGrg @david-boles I know this comment is off by almost 2 1/2 years, but I have just made type declarations for this package that will become available through DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped) soon.

You will soon be able to import the package's functions and Options interface (with TypeScript) by installing these types:


```typescript
npm install @types/bicubic-interpolate
```

**Comment by david-boles** [comment]
Thanks @BrUSomania! I'd be happy to approve a PR if any changes to this repo are warranted.

**Comment by BrUSomania** [comment]
Thank you, @david-boles. I will keep in touch should it be necessary 😊

Here is the source code for the type declarations:
[https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bicubic-interpolate]()
